### ISSUE TITLE
Duplicate characters not handled.

### ISSUE THREAD

**Issue by konkers** [enewey/ff4fe-tracker#9]
One can encounter the same character multiple times.  The tracker does not have any facility to tracking this.

**Comment by enewey** [comment]
So, the tracker already allows you to set characters to multiple different locations. 

One thing unaccounted for is you cannot set a single character to the same location twice. I don't even know if the FF4FE can be randomized to encounter the same character twice in one location. Maybe it can? I've personally never seen it, but might be something to consider.

**Comment by konkers** [comment]
Weird.  I thought I tried it.   It's working now though.  I'll close for now and re-open if it turns out to be a bug.
